INSERT INTO products (
    id, sku, name, description, category, price, currency,
    image_url, status, created_at, updated_at, version
)
VALUES
(
    'c5b9c2d1-7c79-5ed5-ace0-e4418063180b',
    'ELE-0001',
    'Wireless Earbuds',
    'Wireless Earbuds from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    9.24,
    'USD',
    '/static/img/products/catalog/electronics/ele-0001.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '0f5c71e3-4a46-5806-a90b-b8936f9d945c',
    'ELE-0002',
    'Bluetooth Speaker',
    'Bluetooth Speaker from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    12.49,
    'USD',
    '/static/img/products/catalog/electronics/ele-0002.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '7d4267f3-e9e6-53ff-9a19-6fddea38e01a',
    'ELE-0003',
    'Mechanical Keyboard',
    'Mechanical Keyboard from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    15.74,
    'USD',
    '/static/img/products/catalog/electronics/ele-0003.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '131564e6-f4b8-544f-bcfb-00542b8d8bff',
    'ELE-0004',
    'Gaming Mouse',
    'Gaming Mouse from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    18.99,
    'USD',
    '/static/img/products/catalog/electronics/ele-0004.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd3a81a80-7dd1-5854-a3ce-93e60e1474df',
    'ELE-0005',
    'USB-C Hub',
    'USB-C Hub from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    22.24,
    'USD',
    '/static/img/products/catalog/electronics/ele-0005.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9d13c721-7e1f-500a-b4f8-5ccfaaaa937e',
    'ELE-0006',
    'Portable SSD',
    'Portable SSD from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    25.49,
    'USD',
    '/static/img/products/catalog/electronics/ele-0006.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ce066c8b-f06e-547d-a6bd-fa002ce94660',
    'ELE-0007',
    'Smartphone Stand',
    'Smartphone Stand from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    28.74,
    'USD',
    '/static/img/products/catalog/electronics/ele-0007.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c3885e92-d4bc-56dd-baca-558a7ae349ac',
    'ELE-0008',
    'Webcam',
    'Webcam from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    31.99,
    'USD',
    '/static/img/products/catalog/electronics/ele-0008.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1b86a8a9-66e3-5ad4-bd0f-96e13790bb56',
    'ELE-0009',
    'Power Bank',
    'Power Bank from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    35.24,
    'USD',
    '/static/img/products/catalog/electronics/ele-0009.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f4b1dfdf-3392-5ee2-96c8-7ed3690115b5',
    'ELE-0010',
    'Noise Cancelling Headphones',
    'Noise Cancelling Headphones from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    38.49,
    'USD',
    '/static/img/products/catalog/electronics/ele-0010.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '72665e7c-4171-588d-95d6-45a94f96060b',
    'ELE-0011',
    'Smart Watch',
    'Smart Watch from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    41.74,
    'USD',
    '/static/img/products/catalog/electronics/ele-0011.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd841fe3f-29fd-505a-bf15-d761ddc5f1d6',
    'ELE-0012',
    'Fitness Band',
    'Fitness Band from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    44.99,
    'USD',
    '/static/img/products/catalog/electronics/ele-0012.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '841077ad-a248-50f4-93e2-ea4c5262755b',
    'ELE-0013',
    'Tablet Sleeve',
    'Tablet Sleeve from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    48.24,
    'USD',
    '/static/img/products/catalog/electronics/ele-0013.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '71ea9713-5aae-587d-8fcf-822307dcaf51',
    'ELE-0014',
    'Laptop Stand',
    'Laptop Stand from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    51.49,
    'USD',
    '/static/img/products/catalog/electronics/ele-0014.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '135ed9e0-eb81-5088-b0ef-48f6d66bb524',
    'ELE-0015',
    'Wireless Charger',
    'Wireless Charger from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    54.74,
    'USD',
    '/static/img/products/catalog/electronics/ele-0015.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'e4d895cc-92f5-5464-9d5f-bbfcb67f0fe8',
    'ELE-0016',
    'Action Camera',
    'Action Camera from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    57.99,
    'USD',
    '/static/img/products/catalog/electronics/ele-0016.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'e8a8444a-e8d0-551f-8943-2c29df790fa2',
    'ELE-0017',
    'Mini Projector',
    'Mini Projector from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    61.24,
    'USD',
    '/static/img/products/catalog/electronics/ele-0017.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '80f951af-3218-5ffb-8901-f8ac4ebf2b49',
    'ELE-0018',
    'Streaming Microphone',
    'Streaming Microphone from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    64.49,
    'USD',
    '/static/img/products/catalog/electronics/ele-0018.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '394c97e0-ac55-543d-ba9a-5a85151d7839',
    'ELE-0019',
    'LED Desk Lamp',
    'LED Desk Lamp from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    67.74,
    'USD',
    '/static/img/products/catalog/electronics/ele-0019.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '81801af1-9b2b-5f6e-ad88-bcf78875020b',
    'ELE-0020',
    'Digital Alarm Clock',
    'Digital Alarm Clock from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    70.99,
    'USD',
    '/static/img/products/catalog/electronics/ele-0020.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '42a0bd96-e1f2-5b56-b00c-fe1437e2fba1',
    'ELE-0021',
    'Travel Adapter',
    'Travel Adapter from our electronics collection, selected for everyday use, reliable quality, and modern design.',
    'electronics',
    74.24,
    'USD',
    '/static/img/products/catalog/electronics/ele-0021.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f0b790f7-8b9b-5b56-9882-0aa8b723e947',
    'FAS-0022',
    'Classic T-Shirt',
    'Classic T-Shirt from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    77.49,
    'USD',
    '/static/img/products/catalog/fashion/fas-0022.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '63a2b691-9007-5b5a-b752-7335e06ae21b',
    'FAS-0023',
    'Oxford Shirt',
    'Oxford Shirt from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    80.74,
    'USD',
    '/static/img/products/catalog/fashion/fas-0023.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '6544aa1d-860b-5878-a428-59ec7cae1719',
    'FAS-0024',
    'Slim Fit Jeans',
    'Slim Fit Jeans from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    83.99,
    'USD',
    '/static/img/products/catalog/fashion/fas-0024.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '0d9c1e98-01c8-5ffe-bc68-323c0a4b2fc4',
    'FAS-0025',
    'Casual Hoodie',
    'Casual Hoodie from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    87.24,
    'USD',
    '/static/img/products/catalog/fashion/fas-0025.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '3254d19d-d2bd-5df8-a708-26f3dd88c299',
    'FAS-0026',
    'Denim Jacket',
    'Denim Jacket from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    90.49,
    'USD',
    '/static/img/products/catalog/fashion/fas-0026.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '8fb60c0e-2835-5ffb-a2a7-62e93e551a2f',
    'FAS-0027',
    'Summer Dress',
    'Summer Dress from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    93.74,
    'USD',
    '/static/img/products/catalog/fashion/fas-0027.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '6f04996f-a7c4-5e6c-8c52-0fd1bd61631f',
    'FAS-0028',
    'Pleated Skirt',
    'Pleated Skirt from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    96.99,
    'USD',
    '/static/img/products/catalog/fashion/fas-0028.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2a2cb8c3-a0a1-55da-afa7-eda51baa6d31',
    'FAS-0029',
    'Chino Trousers',
    'Chino Trousers from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    100.24,
    'USD',
    '/static/img/products/catalog/fashion/fas-0029.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '0016f58e-c092-5a5f-937e-66d0d2192174',
    'FAS-0030',
    'Polo Shirt',
    'Polo Shirt from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    103.49,
    'USD',
    '/static/img/products/catalog/fashion/fas-0030.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '8bd21057-fea5-5454-b4ba-7700be6b0ca9',
    'FAS-0031',
    'Cotton Kurta',
    'Cotton Kurta from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    106.74,
    'USD',
    '/static/img/products/catalog/fashion/fas-0031.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2ccb0fb2-c067-5329-9866-771916c3d037',
    'FAS-0032',
    'Linen Blazer',
    'Linen Blazer from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    109.99,
    'USD',
    '/static/img/products/catalog/fashion/fas-0032.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd66e9cc0-c57c-524d-9c7e-ae476cd82baf',
    'FAS-0033',
    'Track Pants',
    'Track Pants from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    113.24,
    'USD',
    '/static/img/products/catalog/fashion/fas-0033.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'b356eac7-0705-58d8-95b4-1ef047eb35c2',
    'FAS-0034',
    'Cardigan',
    'Cardigan from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    116.49,
    'USD',
    '/static/img/products/catalog/fashion/fas-0034.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'fd7e4187-1a7a-54ce-91aa-ea23654a0360',
    'FAS-0035',
    'Bomber Jacket',
    'Bomber Jacket from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    119.74,
    'USD',
    '/static/img/products/catalog/fashion/fas-0035.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '247312f5-3f09-5e3c-9bde-0942d4057e33',
    'FAS-0036',
    'Cargo Shorts',
    'Cargo Shorts from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    122.99,
    'USD',
    '/static/img/products/catalog/fashion/fas-0036.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ad2902d1-61e6-5f16-b12c-c0e9c9616182',
    'FAS-0037',
    'Printed Scarf',
    'Printed Scarf from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    126.24,
    'USD',
    '/static/img/products/catalog/fashion/fas-0037.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c06b955f-b5ee-5e36-8e42-d205124ed3eb',
    'FAS-0038',
    'Rain Jacket',
    'Rain Jacket from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    129.49,
    'USD',
    '/static/img/products/catalog/fashion/fas-0038.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2cb734af-ddd1-5d1c-94bb-5034389b366f',
    'FAS-0039',
    'Thermal Top',
    'Thermal Top from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    132.74,
    'USD',
    '/static/img/products/catalog/fashion/fas-0039.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '7698cb84-ebe5-5266-9fcd-d197cc3ae2a7',
    'FAS-0040',
    'Formal Trousers',
    'Formal Trousers from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    135.99,
    'USD',
    '/static/img/products/catalog/fashion/fas-0040.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a0b1887d-d0a0-5849-baf9-a87d3ed12107',
    'FAS-0041',
    'Casual Shirt',
    'Casual Shirt from our fashion collection, selected for everyday use, reliable quality, and modern design.',
    'fashion',
    139.24,
    'USD',
    '/static/img/products/catalog/fashion/fas-0041.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a799b349-abe6-5cfd-8cda-6b622c7d8c6d',
    'FOO-0042',
    'Running Shoes',
    'Running Shoes from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    142.49,
    'USD',
    '/static/img/products/catalog/footwear/foo-0042.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1006cc59-c377-591e-a6d4-767e2ce6ba0d',
    'FOO-0043',
    'Canvas Sneakers',
    'Canvas Sneakers from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    145.74,
    'USD',
    '/static/img/products/catalog/footwear/foo-0043.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '369d0cdf-55cd-5d05-969b-038e44f12ff7',
    'FOO-0044',
    'Leather Boots',
    'Leather Boots from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    148.99,
    'USD',
    '/static/img/products/catalog/footwear/foo-0044.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '99f8cd48-8b0a-5f40-bab8-c978267d2d6a',
    'FOO-0045',
    'Sports Sandals',
    'Sports Sandals from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    152.24,
    'USD',
    '/static/img/products/catalog/footwear/foo-0045.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '66de6e72-be18-5dda-9840-c9841c85496c',
    'FOO-0046',
    'Formal Oxfords',
    'Formal Oxfords from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    155.49,
    'USD',
    '/static/img/products/catalog/footwear/foo-0046.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '5e74edeb-05a4-5048-95b9-d74272b0c3d6',
    'FOO-0047',
    'Walking Shoes',
    'Walking Shoes from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    158.74,
    'USD',
    '/static/img/products/catalog/footwear/foo-0047.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'eddfca31-5bb6-5a06-ad26-21c7cf2c8bfc',
    'FOO-0048',
    'Slip On Sneakers',
    'Slip On Sneakers from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    161.99,
    'USD',
    '/static/img/products/catalog/footwear/foo-0048.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'b09842ff-42a9-5dea-80be-28e6eaffe83e',
    'FOO-0049',
    'Hiking Boots',
    'Hiking Boots from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    165.24,
    'USD',
    '/static/img/products/catalog/footwear/foo-0049.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f4d35310-0069-5eee-959e-05d8a385894f',
    'FOO-0050',
    'Ballet Flats',
    'Ballet Flats from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    168.49,
    'USD',
    '/static/img/products/catalog/footwear/foo-0050.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2ad870f7-9875-560c-b613-ceee25f8a4a1',
    'FOO-0051',
    'Classic Pumps',
    'Classic Pumps from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    171.74,
    'USD',
    '/static/img/products/catalog/footwear/foo-0051.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ee68f33e-2cc1-524f-a01e-8aae78791737',
    'FOO-0052',
    'Flip Flops',
    'Flip Flops from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    174.99,
    'USD',
    '/static/img/products/catalog/footwear/foo-0052.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a408f037-311a-531a-a2c3-cf59a07716ec',
    'FOO-0053',
    'Training Shoes',
    'Training Shoes from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    178.24,
    'USD',
    '/static/img/products/catalog/footwear/foo-0053.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'dfb51bb3-2541-5039-a121-25c4b639b5c9',
    'FOO-0054',
    'Chelsea Boots',
    'Chelsea Boots from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    181.49,
    'USD',
    '/static/img/products/catalog/footwear/foo-0054.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '32b4e528-14fc-5de6-92e0-164e0ac64342',
    'FOO-0055',
    'Boat Shoes',
    'Boat Shoes from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    184.74,
    'USD',
    '/static/img/products/catalog/footwear/foo-0055.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '29473c0e-3d93-50cf-b63c-8c68b6aa0908',
    'FOO-0056',
    'House Slippers',
    'House Slippers from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    187.99,
    'USD',
    '/static/img/products/catalog/footwear/foo-0056.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1e7922e9-9c94-58e6-8626-6510c110f51f',
    'FOO-0057',
    'Trail Shoes',
    'Trail Shoes from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    191.24,
    'USD',
    '/static/img/products/catalog/footwear/foo-0057.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '0ccb4170-4da3-57f9-a3ab-02f68fa79116',
    'FOO-0058',
    'Platform Sandals',
    'Platform Sandals from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    194.49,
    'USD',
    '/static/img/products/catalog/footwear/foo-0058.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2dadd274-ff0e-5c1c-9c82-9c4f86d693e4',
    'FOO-0059',
    'Derby Shoes',
    'Derby Shoes from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    197.74,
    'USD',
    '/static/img/products/catalog/footwear/foo-0059.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2aa35c4f-c7af-5d51-a948-be23784243c8',
    'FOO-0060',
    'Moccasins',
    'Moccasins from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    200.99,
    'USD',
    '/static/img/products/catalog/footwear/foo-0060.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '21a4222b-50cf-5148-b74f-5f30fc1b48b2',
    'FOO-0061',
    'Court Sneakers',
    'Court Sneakers from our footwear collection, selected for everyday use, reliable quality, and modern design.',
    'footwear',
    204.24,
    'USD',
    '/static/img/products/catalog/footwear/foo-0061.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '67459c7a-449e-5abc-bc9b-03ef4147b91a',
    'HOM-0062',
    'Cushion Cover',
    'Cushion Cover from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    207.49,
    'USD',
    '/static/img/products/catalog/home/hom-0062.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ff25640d-2325-56dc-9560-e56118cc81e3',
    'HOM-0063',
    'Table Lamp',
    'Table Lamp from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    210.74,
    'USD',
    '/static/img/products/catalog/home/hom-0063.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c4d2c159-4a05-58da-9ee5-13235ce2e16a',
    'HOM-0064',
    'Wall Clock',
    'Wall Clock from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    213.99,
    'USD',
    '/static/img/products/catalog/home/hom-0064.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ce6701f1-a404-5d61-bae5-65d9c661f943',
    'HOM-0065',
    'Decorative Vase',
    'Decorative Vase from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    217.24,
    'USD',
    '/static/img/products/catalog/home/hom-0065.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'bdfcc987-2903-5089-b810-99db29caf14e',
    'HOM-0066',
    'Photo Frame',
    'Photo Frame from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    220.49,
    'USD',
    '/static/img/products/catalog/home/hom-0066.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '961e3ed0-ef29-553b-b003-b05a522eda34',
    'HOM-0067',
    'Cotton Bedsheet',
    'Cotton Bedsheet from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    223.74,
    'USD',
    '/static/img/products/catalog/home/hom-0067.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '4fada506-81a5-5440-83ec-52965a4c5bf9',
    'HOM-0068',
    'Door Mat',
    'Door Mat from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    226.99,
    'USD',
    '/static/img/products/catalog/home/hom-0068.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '70a1392c-036e-5f3c-bb43-6645ce1484f3',
    'HOM-0069',
    'Storage Basket',
    'Storage Basket from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    230.24,
    'USD',
    '/static/img/products/catalog/home/hom-0069.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ba3df979-ea4b-5da2-a6d6-dac9269391bc',
    'HOM-0070',
    'Scented Candle',
    'Scented Candle from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    233.49,
    'USD',
    '/static/img/products/catalog/home/hom-0070.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '76f0ac6b-924e-574e-9ca7-ced99925b401',
    'HOM-0071',
    'Throw Blanket',
    'Throw Blanket from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    236.74,
    'USD',
    '/static/img/products/catalog/home/hom-0071.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '68e5fccd-3f8f-53dc-8c93-707f7b5901c3',
    'HOM-0072',
    'Wall Shelf',
    'Wall Shelf from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    239.99,
    'USD',
    '/static/img/products/catalog/home/hom-0072.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a0bcf7f1-4c4e-5c2f-bc87-630a94ae1b79',
    'HOM-0073',
    'Laundry Hamper',
    'Laundry Hamper from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    243.24,
    'USD',
    '/static/img/products/catalog/home/hom-0073.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '76cf2296-8c9a-50e2-82be-97f25adb68f3',
    'HOM-0074',
    'Curtain Set',
    'Curtain Set from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    246.49,
    'USD',
    '/static/img/products/catalog/home/hom-0074.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '8a7e7c14-9619-5b34-bd16-b8440ab78d73',
    'HOM-0075',
    'Indoor Planter',
    'Indoor Planter from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    249.74,
    'USD',
    '/static/img/products/catalog/home/hom-0075.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd10e3639-b75a-5d5f-adbd-d3259a473187',
    'HOM-0076',
    'Floor Rug',
    'Floor Rug from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    252.99,
    'USD',
    '/static/img/products/catalog/home/hom-0076.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c4dc818a-e873-5d78-8f74-2c60d3b47bc9',
    'HOM-0077',
    'Desk Organizer',
    'Desk Organizer from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    256.24,
    'USD',
    '/static/img/products/catalog/home/hom-0077.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '7f261cdb-c338-55e2-a1f8-aeea1fd7cc20',
    'HOM-0078',
    'Ceramic Figurine',
    'Ceramic Figurine from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    259.49,
    'USD',
    '/static/img/products/catalog/home/hom-0078.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'b5c9ffb1-1819-5251-96a6-83772ddc0304',
    'HOM-0079',
    'Tissue Box',
    'Tissue Box from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    262.74,
    'USD',
    '/static/img/products/catalog/home/hom-0079.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ccfd1d2b-dd0b-5858-85fb-f844f67c77f4',
    'HOM-0080',
    'Coat Hanger',
    'Coat Hanger from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    5.99,
    'USD',
    '/static/img/products/catalog/home/hom-0080.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '07b04394-d9b1-5e41-8ada-41ef5c8ecce1',
    'HOM-0081',
    'LED String Lights',
    'LED String Lights from our home collection, selected for everyday use, reliable quality, and modern design.',
    'home',
    9.24,
    'USD',
    '/static/img/products/catalog/home/hom-0081.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '3f57071b-6801-5650-8887-e8f5bef31ffa',
    'KIT-0082',
    'Chef Knife',
    'Chef Knife from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    12.49,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0082.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '76a19b97-328e-5df8-a633-b292c41d10f2',
    'KIT-0083',
    'Cutting Board',
    'Cutting Board from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    15.74,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0083.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'eee449ab-17be-5a61-969f-9d53e85a6330',
    'KIT-0084',
    'Mixing Bowl',
    'Mixing Bowl from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    18.99,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0084.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1bf38e43-80ef-56a6-a7e9-3ae187487c00',
    'KIT-0085',
    'Frying Pan',
    'Frying Pan from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    22.24,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0085.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9675c350-9796-597b-acea-5c3a8225cef3',
    'KIT-0086',
    'Saucepan',
    'Saucepan from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    25.49,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0086.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a11186df-4699-579f-994d-adcb64438237',
    'KIT-0087',
    'Coffee Press',
    'Coffee Press from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    28.74,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0087.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9def8c7d-dc42-5b1a-b8dd-29c37260981f',
    'KIT-0088',
    'Water Bottle',
    'Water Bottle from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    31.99,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0088.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '17a80eb4-9f88-58c4-9aff-9868cb10bfec',
    'KIT-0089',
    'Lunch Box',
    'Lunch Box from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    35.24,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0089.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2119d324-3e8c-5b0b-aaba-f0a81266f3b8',
    'KIT-0090',
    'Spice Rack',
    'Spice Rack from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    38.49,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0090.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '777e9e41-c028-51ac-acf8-4ee0e8448ebc',
    'KIT-0091',
    'Measuring Cup Set',
    'Measuring Cup Set from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    41.74,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0091.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9f035591-fee0-5dae-81cc-85a67ba923a6',
    'KIT-0092',
    'Silicone Spatula',
    'Silicone Spatula from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    44.99,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0092.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '00f0eae1-8813-527f-a277-e8f43548ea83',
    'KIT-0093',
    'Vegetable Peeler',
    'Vegetable Peeler from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    48.24,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0093.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c60c15f0-d74c-50b7-82e7-1f4f13cd8594',
    'KIT-0094',
    'Colander',
    'Colander from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    51.49,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0094.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '33db0df2-3dc6-53f7-9126-a3d9f927d988',
    'KIT-0095',
    'Tea Kettle',
    'Tea Kettle from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    54.74,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0095.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'b3fa4783-c636-59c6-9339-651c4f03cc9a',
    'KIT-0096',
    'Serving Tray',
    'Serving Tray from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    57.99,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0096.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '3c2ad566-127a-5eb9-82ed-1af3c6b2713c',
    'KIT-0097',
    'Food Container Set',
    'Food Container Set from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    61.24,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0097.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '35fcf392-fbae-5d2f-9270-5349d7fe227b',
    'KIT-0098',
    'Oven Mitts',
    'Oven Mitts from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    64.49,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0098.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'aa007ee6-a69f-5cc5-9970-1f8ae2b71c15',
    'KIT-0099',
    'Ice Cube Tray',
    'Ice Cube Tray from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    67.74,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0099.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '440f3567-92d5-5a11-9b38-39902f0dcac2',
    'KIT-0100',
    'Grater',
    'Grater from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    70.99,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0100.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '39f43338-947e-57e4-9be0-7adc769e1a94',
    'KIT-0101',
    'Whisk',
    'Whisk from our kitchen collection, selected for everyday use, reliable quality, and modern design.',
    'kitchen',
    74.24,
    'USD',
    '/static/img/products/catalog/kitchen/kit-0101.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a557f1de-e4d3-5391-a308-132a647cc4e9',
    'BEA-0102',
    'Face Cleanser',
    'Face Cleanser from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    77.49,
    'USD',
    '/static/img/products/catalog/beauty/bea-0102.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c1111c01-de46-5416-9000-e8554665e05d',
    'BEA-0103',
    'Moisturizing Cream',
    'Moisturizing Cream from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    80.74,
    'USD',
    '/static/img/products/catalog/beauty/bea-0103.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'aea64c49-ee7a-59ce-8562-b00b7c6d8937',
    'BEA-0104',
    'Sunscreen Lotion',
    'Sunscreen Lotion from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    83.99,
    'USD',
    '/static/img/products/catalog/beauty/bea-0104.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a337e4db-19dd-5941-b05f-845517d118d5',
    'BEA-0105',
    'Lip Balm',
    'Lip Balm from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    87.24,
    'USD',
    '/static/img/products/catalog/beauty/bea-0105.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ec1edd3e-7b04-5bea-a801-81757f73e798',
    'BEA-0106',
    'Body Wash',
    'Body Wash from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    90.49,
    'USD',
    '/static/img/products/catalog/beauty/bea-0106.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '406453c3-2b15-57d0-b77b-f8626f9370ce',
    'BEA-0107',
    'Shampoo',
    'Shampoo from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    93.74,
    'USD',
    '/static/img/products/catalog/beauty/bea-0107.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '57b2ccb6-e246-5dad-a94d-af69fed2bc18',
    'BEA-0108',
    'Conditioner',
    'Conditioner from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    96.99,
    'USD',
    '/static/img/products/catalog/beauty/bea-0108.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '325b5405-d4c6-5c01-a5b0-78f86f8d33b5',
    'BEA-0109',
    'Hair Serum',
    'Hair Serum from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    100.24,
    'USD',
    '/static/img/products/catalog/beauty/bea-0109.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '6cc1cd8c-1c6b-5e0b-af6a-dbef84d0c80e',
    'BEA-0110',
    'Face Mask',
    'Face Mask from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    103.49,
    'USD',
    '/static/img/products/catalog/beauty/bea-0110.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'e5d2af08-da8f-5a62-90b5-96d70e59740f',
    'BEA-0111',
    'Hand Cream',
    'Hand Cream from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    106.74,
    'USD',
    '/static/img/products/catalog/beauty/bea-0111.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '428bcb15-6522-55e5-9068-245d14675e9e',
    'BEA-0112',
    'Makeup Brush Set',
    'Makeup Brush Set from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    109.99,
    'USD',
    '/static/img/products/catalog/beauty/bea-0112.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '56f15deb-b1e9-5f43-ad2f-14d625286768',
    'BEA-0113',
    'Compact Mirror',
    'Compact Mirror from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    113.24,
    'USD',
    '/static/img/products/catalog/beauty/bea-0113.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '4a538414-a76f-5d43-9cd3-c3bd26ee7750',
    'BEA-0114',
    'Nail Care Kit',
    'Nail Care Kit from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    116.49,
    'USD',
    '/static/img/products/catalog/beauty/bea-0114.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '6e7e3cfa-9a98-5d8f-8e4b-56f4cf5e2c39',
    'BEA-0115',
    'Perfume Spray',
    'Perfume Spray from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    119.74,
    'USD',
    '/static/img/products/catalog/beauty/bea-0115.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ce9f01c4-d625-55c7-8b69-ed1d8498211c',
    'BEA-0116',
    'Body Lotion',
    'Body Lotion from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    122.99,
    'USD',
    '/static/img/products/catalog/beauty/bea-0116.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'cfc055fa-84f6-5d81-81a8-03247baf2eec',
    'BEA-0117',
    'Beard Oil',
    'Beard Oil from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    126.24,
    'USD',
    '/static/img/products/catalog/beauty/bea-0117.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '434b6910-6a08-505f-a1fc-4f46d22b340f',
    'BEA-0118',
    'Shaving Brush',
    'Shaving Brush from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    129.49,
    'USD',
    '/static/img/products/catalog/beauty/bea-0118.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f5bfbb97-5918-51de-b114-627e1b7d29d6',
    'BEA-0119',
    'Bath Sponge',
    'Bath Sponge from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    132.74,
    'USD',
    '/static/img/products/catalog/beauty/bea-0119.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'cdc6704d-6f92-5354-99e3-14175f5b6094',
    'BEA-0120',
    'Hair Brush',
    'Hair Brush from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    135.99,
    'USD',
    '/static/img/products/catalog/beauty/bea-0120.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1721bf1f-6e3e-531a-a5d8-f14796baec7f',
    'BEA-0121',
    'Cosmetic Pouch',
    'Cosmetic Pouch from our beauty collection, selected for everyday use, reliable quality, and modern design.',
    'beauty',
    139.24,
    'USD',
    '/static/img/products/catalog/beauty/bea-0121.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '879b4ac1-93d0-576f-90ed-a98844d04580',
    'SPO-0122',
    'Yoga Mat',
    'Yoga Mat from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    142.49,
    'USD',
    '/static/img/products/catalog/sports/spo-0122.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'af382eb8-11b6-5115-89af-471ebbb69e35',
    'SPO-0123',
    'Dumbbell Pair',
    'Dumbbell Pair from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    145.74,
    'USD',
    '/static/img/products/catalog/sports/spo-0123.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'fe19248c-025e-5365-a3c1-c4242289f612',
    'SPO-0124',
    'Resistance Bands',
    'Resistance Bands from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    148.99,
    'USD',
    '/static/img/products/catalog/sports/spo-0124.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '0aa47d57-1a10-50de-973e-0b45d2426115',
    'SPO-0125',
    'Football',
    'Football from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    152.24,
    'USD',
    '/static/img/products/catalog/sports/spo-0125.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd5fa51ed-a020-5d67-9fe2-22272bf11e6a',
    'SPO-0126',
    'Cricket Bat',
    'Cricket Bat from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    155.49,
    'USD',
    '/static/img/products/catalog/sports/spo-0126.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '303a0512-7cfb-5905-b61f-435e9a2bf9e3',
    'SPO-0127',
    'Badminton Racket',
    'Badminton Racket from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    158.74,
    'USD',
    '/static/img/products/catalog/sports/spo-0127.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'dea156a5-466f-5b39-9fa4-3d8ddbec37f8',
    'SPO-0128',
    'Skipping Rope',
    'Skipping Rope from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    161.99,
    'USD',
    '/static/img/products/catalog/sports/spo-0128.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9390022a-ddb1-5067-b5c1-4aadaf6e1d53',
    'SPO-0129',
    'Gym Gloves',
    'Gym Gloves from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    165.24,
    'USD',
    '/static/img/products/catalog/sports/spo-0129.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '0ec93fc3-375e-504c-a3d7-83d29175aef9',
    'SPO-0130',
    'Cycling Helmet',
    'Cycling Helmet from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    168.49,
    'USD',
    '/static/img/products/catalog/sports/spo-0130.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9f6ae8ea-d3eb-5bc7-8848-18b0a40d9faa',
    'SPO-0131',
    'Water Flask',
    'Water Flask from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    171.74,
    'USD',
    '/static/img/products/catalog/sports/spo-0131.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a85a1a88-8461-560e-89bd-d654113189f6',
    'SPO-0132',
    'Tennis Balls',
    'Tennis Balls from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    174.99,
    'USD',
    '/static/img/products/catalog/sports/spo-0132.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '3933f211-d6e8-540f-a3e4-d8d45e256fef',
    'SPO-0133',
    'Basketball',
    'Basketball from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    178.24,
    'USD',
    '/static/img/products/catalog/sports/spo-0133.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1c4174bc-a414-59e1-b978-d940d4bd7d91',
    'SPO-0134',
    'Foam Roller',
    'Foam Roller from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    181.49,
    'USD',
    '/static/img/products/catalog/sports/spo-0134.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '33f4331d-d6fb-5ad9-ad72-3ccd6f62836e',
    'SPO-0135',
    'Sports Towel',
    'Sports Towel from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    184.74,
    'USD',
    '/static/img/products/catalog/sports/spo-0135.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '6433bbbd-cd22-59eb-b12a-e7c0c35e239d',
    'SPO-0136',
    'Knee Support',
    'Knee Support from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    187.99,
    'USD',
    '/static/img/products/catalog/sports/spo-0136.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a625c5f5-f9bf-5045-b5ea-2e3a84195983',
    'SPO-0137',
    'Swimming Goggles',
    'Swimming Goggles from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    191.24,
    'USD',
    '/static/img/products/catalog/sports/spo-0137.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'b5a7a152-a836-5bc0-90d7-ba58e6c9f241',
    'SPO-0138',
    'Table Tennis Set',
    'Table Tennis Set from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    194.49,
    'USD',
    '/static/img/products/catalog/sports/spo-0138.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd04b7a0b-8f7b-5674-92b2-f439a1955c81',
    'SPO-0139',
    'Running Belt',
    'Running Belt from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    197.74,
    'USD',
    '/static/img/products/catalog/sports/spo-0139.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '303739b3-758e-5bbc-aa8a-cde7f66b39af',
    'SPO-0140',
    'Exercise Ball',
    'Exercise Ball from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    200.99,
    'USD',
    '/static/img/products/catalog/sports/spo-0140.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '5b3ae50b-ae64-5ae2-8fe6-37dcb7d3d348',
    'SPO-0141',
    'Gym Bag',
    'Gym Bag from our sports collection, selected for everyday use, reliable quality, and modern design.',
    'sports',
    204.24,
    'USD',
    '/static/img/products/catalog/sports/spo-0141.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'fc442784-bc34-5422-8726-b9576e7a574b',
    'BOO-0142',
    'Cloud Architecture Guide',
    'Cloud Architecture Guide from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    207.49,
    'USD',
    '/static/img/products/catalog/books/boo-0142.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '02b8dd1b-d0e5-5631-a51a-9e345e7fab24',
    'BOO-0143',
    'Kubernetes Handbook',
    'Kubernetes Handbook from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    210.74,
    'USD',
    '/static/img/products/catalog/books/boo-0143.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a17002a7-3692-5fb1-9006-b2eef7942720',
    'BOO-0144',
    'DevOps Field Manual',
    'DevOps Field Manual from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    213.99,
    'USD',
    '/static/img/products/catalog/books/boo-0144.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '4d566dd7-6c5c-5e26-9ac8-65d25ad1c35c',
    'BOO-0145',
    'Linux Administration',
    'Linux Administration from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    217.24,
    'USD',
    '/static/img/products/catalog/books/boo-0145.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1853aa07-7ad7-575e-ad6e-d8e8b9357db0',
    'BOO-0146',
    'Terraform in Practice',
    'Terraform in Practice from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    220.49,
    'USD',
    '/static/img/products/catalog/books/boo-0146.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd91470f1-9d4a-5e21-90f0-1ffae984afde',
    'BOO-0147',
    'Java Microservices',
    'Java Microservices from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    223.74,
    'USD',
    '/static/img/products/catalog/books/boo-0147.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'cc1417b7-6fc8-56c3-900c-eb90114da47b',
    'BOO-0148',
    'React Fundamentals',
    'React Fundamentals from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    226.99,
    'USD',
    '/static/img/products/catalog/books/boo-0148.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '0bcfed55-3d58-5d74-8614-1e3269c7594a',
    'BOO-0149',
    'System Design Notes',
    'System Design Notes from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    230.24,
    'USD',
    '/static/img/products/catalog/books/boo-0149.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c3d5e708-bc12-5afe-8b98-4f43d490d7ba',
    'BOO-0150',
    'Database Essentials',
    'Database Essentials from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    233.49,
    'USD',
    '/static/img/products/catalog/books/boo-0150.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c02de598-d6bd-5a8d-8dec-b99d4ec7e0ab',
    'BOO-0151',
    'Site Reliability Engineering',
    'Site Reliability Engineering from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    236.74,
    'USD',
    '/static/img/products/catalog/books/boo-0151.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '7bd317a0-22e0-5bf7-abd2-e83bb617ef3c',
    'BOO-0152',
    'Python Automation',
    'Python Automation from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    239.99,
    'USD',
    '/static/img/products/catalog/books/boo-0152.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '31af8f19-88d6-5963-bca5-906678529c27',
    'BOO-0153',
    'Networking Basics',
    'Networking Basics from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    243.24,
    'USD',
    '/static/img/products/catalog/books/boo-0153.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '683e8660-897c-5e49-91bd-e296e6c972c3',
    'BOO-0154',
    'API Design Patterns',
    'API Design Patterns from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    246.49,
    'USD',
    '/static/img/products/catalog/books/boo-0154.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'a7a67ac9-e2d1-5e7d-9c58-204687ea3324',
    'BOO-0155',
    'Docker Deep Dive',
    'Docker Deep Dive from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    249.74,
    'USD',
    '/static/img/products/catalog/books/boo-0155.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '3aea3aa4-c9f0-5d4b-964e-0a3828bde276',
    'BOO-0156',
    'AWS Solutions Guide',
    'AWS Solutions Guide from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    252.99,
    'USD',
    '/static/img/products/catalog/books/boo-0156.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '5f3841fd-1a5d-5c54-bce4-b067f08c659a',
    'BOO-0157',
    'Cybersecurity Basics',
    'Cybersecurity Basics from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    256.24,
    'USD',
    '/static/img/products/catalog/books/boo-0157.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1284728c-7b70-5f7a-8f2f-938346ad8a83',
    'BOO-0158',
    'Git Workflow Guide',
    'Git Workflow Guide from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    259.49,
    'USD',
    '/static/img/products/catalog/books/boo-0158.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '7d5d3835-9e00-54b2-b4c9-5ff8e0d53f21',
    'BOO-0159',
    'Observability Handbook',
    'Observability Handbook from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    262.74,
    'USD',
    '/static/img/products/catalog/books/boo-0159.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '4680948e-f36c-53d8-98e4-de6357834399',
    'BOO-0160',
    'Distributed Systems',
    'Distributed Systems from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    5.99,
    'USD',
    '/static/img/products/catalog/books/boo-0160.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '11fab4cb-2242-58b3-9829-04a7db6aee26',
    'BOO-0161',
    'Technical Interview Prep',
    'Technical Interview Prep from our books collection, selected for everyday use, reliable quality, and modern design.',
    'books',
    9.24,
    'USD',
    '/static/img/products/catalog/books/boo-0161.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '5172ba74-65f8-553c-bb77-2364aaacfb5c',
    'TOY-0162',
    'Building Blocks',
    'Building Blocks from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    12.49,
    'USD',
    '/static/img/products/catalog/toys/toy-0162.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '925dcc7e-6a2b-5a4c-bb48-bcc119aef17b',
    'TOY-0163',
    'Remote Control Car',
    'Remote Control Car from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    15.74,
    'USD',
    '/static/img/products/catalog/toys/toy-0163.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd130b028-45f2-5e6b-b8b2-90a410ec95d7',
    'TOY-0164',
    'Puzzle Cube',
    'Puzzle Cube from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    18.99,
    'USD',
    '/static/img/products/catalog/toys/toy-0164.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '35d714f0-d43b-5721-a532-981ae82f4eef',
    'TOY-0165',
    'Wooden Train',
    'Wooden Train from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    22.24,
    'USD',
    '/static/img/products/catalog/toys/toy-0165.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '962cf59e-f430-53b6-acf5-b50927970840',
    'TOY-0166',
    'Stuffed Bear',
    'Stuffed Bear from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    25.49,
    'USD',
    '/static/img/products/catalog/toys/toy-0166.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9cc3aa79-b548-59e3-aa83-8f440af2121a',
    'TOY-0167',
    'Art Kit',
    'Art Kit from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    28.74,
    'USD',
    '/static/img/products/catalog/toys/toy-0167.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9f342c93-7bd1-5255-b93d-3d92d3d36af2',
    'TOY-0168',
    'Science Experiment Set',
    'Science Experiment Set from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    31.99,
    'USD',
    '/static/img/products/catalog/toys/toy-0168.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f573db8b-4874-571f-af5c-8fd42ebec559',
    'TOY-0169',
    'Mini Basketball Hoop',
    'Mini Basketball Hoop from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    35.24,
    'USD',
    '/static/img/products/catalog/toys/toy-0169.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1f75699c-a3ff-5a4f-80c7-d6f6babff328',
    'TOY-0170',
    'Doll House',
    'Doll House from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    38.49,
    'USD',
    '/static/img/products/catalog/toys/toy-0170.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '7182d424-5e14-54fa-9164-9325ac7b1156',
    'TOY-0171',
    'Toy Robot',
    'Toy Robot from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    41.74,
    'USD',
    '/static/img/products/catalog/toys/toy-0171.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'cd2ffb7e-86f6-5053-8e0b-3373f14f9109',
    'TOY-0172',
    'Magnetic Tiles',
    'Magnetic Tiles from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    44.99,
    'USD',
    '/static/img/products/catalog/toys/toy-0172.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '23707d57-46c0-5d22-9754-c8cefcf4a150',
    'TOY-0173',
    'Board Game',
    'Board Game from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    48.24,
    'USD',
    '/static/img/products/catalog/toys/toy-0173.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'add5f2ab-32bb-5158-a503-949915db26ab',
    'TOY-0174',
    'Water Gun',
    'Water Gun from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    51.49,
    'USD',
    '/static/img/products/catalog/toys/toy-0174.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9586fcfb-c511-514f-8c0d-9cb56467b8d2',
    'TOY-0175',
    'Musical Keyboard Toy',
    'Musical Keyboard Toy from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    54.74,
    'USD',
    '/static/img/products/catalog/toys/toy-0175.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd0ee6aee-30d9-5f72-82d3-42d6377f9720',
    'TOY-0176',
    'Animal Figure Set',
    'Animal Figure Set from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    57.99,
    'USD',
    '/static/img/products/catalog/toys/toy-0176.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ab67dc7e-4da1-53d7-854e-aebda1956da9',
    'TOY-0177',
    'Model Airplane',
    'Model Airplane from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    61.24,
    'USD',
    '/static/img/products/catalog/toys/toy-0177.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '313110e3-ae47-5a6a-8813-db042f10a576',
    'TOY-0178',
    'Kids Tool Set',
    'Kids Tool Set from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    64.49,
    'USD',
    '/static/img/products/catalog/toys/toy-0178.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '21dee6f9-465b-5111-8bf5-0df86d655e2f',
    'TOY-0179',
    'Story Cards',
    'Story Cards from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    67.74,
    'USD',
    '/static/img/products/catalog/toys/toy-0179.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c1d0add1-847f-58f3-b906-152bf7bfa250',
    'TOY-0180',
    'Shape Sorter',
    'Shape Sorter from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    70.99,
    'USD',
    '/static/img/products/catalog/toys/toy-0180.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '130ac5c5-35d0-565a-92be-0979f838b1d5',
    'TOY-0181',
    'Play Tent',
    'Play Tent from our toys collection, selected for everyday use, reliable quality, and modern design.',
    'toys',
    74.24,
    'USD',
    '/static/img/products/catalog/toys/toy-0181.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'e25131da-86ff-5f30-8417-7d951aee92ab',
    'GRO-0182',
    'Organic Oats',
    'Organic Oats from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    77.49,
    'USD',
    '/static/img/products/catalog/grocery/gro-0182.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '91639dd6-9cef-5373-aa66-19af5ef46777',
    'GRO-0183',
    'Brown Rice',
    'Brown Rice from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    80.74,
    'USD',
    '/static/img/products/catalog/grocery/gro-0183.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '474def10-6afd-5101-b0b6-106fcc0891a8',
    'GRO-0184',
    'Green Tea',
    'Green Tea from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    83.99,
    'USD',
    '/static/img/products/catalog/grocery/gro-0184.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '02684a9f-be96-546c-a85a-ffb920c6414c',
    'GRO-0185',
    'Roasted Almonds',
    'Roasted Almonds from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    87.24,
    'USD',
    '/static/img/products/catalog/grocery/gro-0185.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '73973fe8-d3f9-532c-a7e5-27920d314267',
    'GRO-0186',
    'Peanut Butter',
    'Peanut Butter from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    90.49,
    'USD',
    '/static/img/products/catalog/grocery/gro-0186.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '6d03bb80-6d62-546b-95fd-8b28d99ffb98',
    'GRO-0187',
    'Whole Wheat Pasta',
    'Whole Wheat Pasta from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    93.74,
    'USD',
    '/static/img/products/catalog/grocery/gro-0187.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f81dea22-fb47-5313-8545-f968d989449a',
    'GRO-0188',
    'Dark Chocolate',
    'Dark Chocolate from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    96.99,
    'USD',
    '/static/img/products/catalog/grocery/gro-0188.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '0cee5903-e096-541e-8dde-001a4acd76be',
    'GRO-0189',
    'Honey Jar',
    'Honey Jar from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    100.24,
    'USD',
    '/static/img/products/catalog/grocery/gro-0189.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '40830eae-a198-5091-a909-1cd2be14b169',
    'GRO-0190',
    'Mixed Seeds',
    'Mixed Seeds from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    103.49,
    'USD',
    '/static/img/products/catalog/grocery/gro-0190.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'cdf7a3d4-635f-5bf4-be57-487dc9a79482',
    'GRO-0191',
    'Granola',
    'Granola from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    106.74,
    'USD',
    '/static/img/products/catalog/grocery/gro-0191.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f429da98-c3ce-5978-8722-59547440c2b4',
    'GRO-0192',
    'Coffee Beans',
    'Coffee Beans from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    109.99,
    'USD',
    '/static/img/products/catalog/grocery/gro-0192.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2a9f8741-bc05-5c90-967f-2c08a92deb2f',
    'GRO-0193',
    'Herbal Tea',
    'Herbal Tea from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    113.24,
    'USD',
    '/static/img/products/catalog/grocery/gro-0193.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c9fa29af-37d7-50ba-8a3e-844bcc0ca260',
    'GRO-0194',
    'Dried Cranberries',
    'Dried Cranberries from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    116.49,
    'USD',
    '/static/img/products/catalog/grocery/gro-0194.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '823e9e03-8a31-585f-9e41-fed814acb690',
    'GRO-0195',
    'Olive Oil',
    'Olive Oil from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    119.74,
    'USD',
    '/static/img/products/catalog/grocery/gro-0195.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '8e500075-3b7e-5578-9aa5-cc02e7292e0d',
    'GRO-0196',
    'Tomato Sauce',
    'Tomato Sauce from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    122.99,
    'USD',
    '/static/img/products/catalog/grocery/gro-0196.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '02320584-8ab5-57fa-8531-ad456fe4c4c9',
    'GRO-0197',
    'Breakfast Cereal',
    'Breakfast Cereal from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    126.24,
    'USD',
    '/static/img/products/catalog/grocery/gro-0197.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '216e2568-bdf0-5529-abf9-91e1f1936873',
    'GRO-0198',
    'Protein Bars',
    'Protein Bars from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    129.49,
    'USD',
    '/static/img/products/catalog/grocery/gro-0198.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'e63ee302-cf05-5bdc-aa8e-086e54febab0',
    'GRO-0199',
    'Cashew Nuts',
    'Cashew Nuts from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    132.74,
    'USD',
    '/static/img/products/catalog/grocery/gro-0199.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'e3d651ab-9fe3-54f3-96c3-163430edcd9a',
    'GRO-0200',
    'Fruit Jam',
    'Fruit Jam from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    135.99,
    'USD',
    '/static/img/products/catalog/grocery/gro-0200.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '80d46cad-15a6-5308-bca4-74dc3362dd93',
    'GRO-0201',
    'Coconut Water',
    'Coconut Water from our grocery collection, selected for everyday use, reliable quality, and modern design.',
    'grocery',
    139.24,
    'USD',
    '/static/img/products/catalog/grocery/gro-0201.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '99295955-fa61-5be7-a26a-8ecb7a7f771a',
    'OFF-0202',
    'Notebook Set',
    'Notebook Set from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    142.49,
    'USD',
    '/static/img/products/catalog/office/off-0202.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '30255ca1-374d-587c-bb74-0ba6046990b2',
    'OFF-0203',
    'Gel Pen Pack',
    'Gel Pen Pack from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    145.74,
    'USD',
    '/static/img/products/catalog/office/off-0203.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2a4e9c15-1928-5814-88ec-02cf2e35969b',
    'OFF-0204',
    'Desk Calendar',
    'Desk Calendar from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    148.99,
    'USD',
    '/static/img/products/catalog/office/off-0204.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'c96d24db-8aa6-50d2-8689-fdc1700a2ba2',
    'OFF-0205',
    'Stapler',
    'Stapler from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    152.24,
    'USD',
    '/static/img/products/catalog/office/off-0205.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '9336a1cb-08a1-5f71-af33-025a8fdeb42b',
    'OFF-0206',
    'Paper Clips',
    'Paper Clips from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    155.49,
    'USD',
    '/static/img/products/catalog/office/off-0206.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '4b055fee-3407-5cd0-b207-ac2595dacf37',
    'OFF-0207',
    'File Organizer',
    'File Organizer from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    158.74,
    'USD',
    '/static/img/products/catalog/office/off-0207.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1fa12880-d232-58a4-883b-e4918444127c',
    'OFF-0208',
    'Sticky Notes',
    'Sticky Notes from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    161.99,
    'USD',
    '/static/img/products/catalog/office/off-0208.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '5ff283f9-db1b-59c6-bc47-bd6edb9c2ce7',
    'OFF-0209',
    'Whiteboard Markers',
    'Whiteboard Markers from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    165.24,
    'USD',
    '/static/img/products/catalog/office/off-0209.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '74ddd8f4-e2f9-5a2e-8b6c-e928d8b3cd51',
    'OFF-0210',
    'Desk Pad',
    'Desk Pad from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    168.49,
    'USD',
    '/static/img/products/catalog/office/off-0210.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'b4800d37-398d-5770-bd9c-7c73302bb0e8',
    'OFF-0211',
    'Laptop Backpack',
    'Laptop Backpack from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    171.74,
    'USD',
    '/static/img/products/catalog/office/off-0211.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '6d57645c-46cf-58e7-a751-84fefaf095d8',
    'OFF-0212',
    'Document Folder',
    'Document Folder from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    174.99,
    'USD',
    '/static/img/products/catalog/office/off-0212.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '54fad04e-59ab-59b0-9208-5bc90da5ae04',
    'OFF-0213',
    'Calculator',
    'Calculator from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    178.24,
    'USD',
    '/static/img/products/catalog/office/off-0213.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '74bcbe6d-4f36-5b22-9aa0-87791ca0ebf5',
    'OFF-0214',
    'Pen Stand',
    'Pen Stand from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    181.49,
    'USD',
    '/static/img/products/catalog/office/off-0214.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '215eb8df-06f5-515d-8a07-d0e65a99688e',
    'OFF-0215',
    'Scissors',
    'Scissors from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    184.74,
    'USD',
    '/static/img/products/catalog/office/off-0215.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '10378e15-6474-55c2-bfc1-da1f57b3d61e',
    'OFF-0216',
    'Tape Dispenser',
    'Tape Dispenser from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    187.99,
    'USD',
    '/static/img/products/catalog/office/off-0216.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '797ac6b6-eb38-5a4c-9aef-6d318e74fbf8',
    'OFF-0217',
    'Index Cards',
    'Index Cards from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    191.24,
    'USD',
    '/static/img/products/catalog/office/off-0217.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '837f2e63-af61-5b8f-ba0d-4b1400bd4175',
    'OFF-0218',
    'Binder Clips',
    'Binder Clips from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    194.49,
    'USD',
    '/static/img/products/catalog/office/off-0218.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd5f51e6d-e2c8-562e-8c0d-e08007ae40eb',
    'OFF-0219',
    'Mouse Pad',
    'Mouse Pad from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    197.74,
    'USD',
    '/static/img/products/catalog/office/off-0219.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd6ae17fe-dcda-54f6-a5c9-de14eadcc62f',
    'OFF-0220',
    'Cable Organizer',
    'Cable Organizer from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    200.99,
    'USD',
    '/static/img/products/catalog/office/off-0220.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '8c2793ab-f865-514d-a899-08c961246829',
    'OFF-0221',
    'Name Badge Holder',
    'Name Badge Holder from our office collection, selected for everyday use, reliable quality, and modern design.',
    'office',
    204.24,
    'USD',
    '/static/img/products/catalog/office/off-0221.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '5d13bc20-2130-5d31-8aae-0ec1d034809b',
    'ACC-0222',
    'Leather Wallet',
    'Leather Wallet from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    207.49,
    'USD',
    '/static/img/products/catalog/accessories/acc-0222.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '1b280887-70d5-5d01-aac5-83f367836f2e',
    'ACC-0223',
    'Canvas Belt',
    'Canvas Belt from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    210.74,
    'USD',
    '/static/img/products/catalog/accessories/acc-0223.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '38cf96fa-5b09-5928-94b2-ee8c635bb520',
    'ACC-0224',
    'Travel Backpack',
    'Travel Backpack from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    213.99,
    'USD',
    '/static/img/products/catalog/accessories/acc-0224.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'ccf7161e-7105-57cf-8b20-96679f936039',
    'ACC-0225',
    'Crossbody Bag',
    'Crossbody Bag from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    217.24,
    'USD',
    '/static/img/products/catalog/accessories/acc-0225.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'fee30039-9d36-515e-8036-268816ab276b',
    'ACC-0226',
    'Baseball Cap',
    'Baseball Cap from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    220.49,
    'USD',
    '/static/img/products/catalog/accessories/acc-0226.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'b5ba8efa-cf77-5b01-a4ff-f52cd229f980',
    'ACC-0227',
    'Wool Beanie',
    'Wool Beanie from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    223.74,
    'USD',
    '/static/img/products/catalog/accessories/acc-0227.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'e7999670-1f85-56c5-8130-35fd6a0e119b',
    'ACC-0228',
    'Laptop Messenger Bag',
    'Laptop Messenger Bag from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    226.99,
    'USD',
    '/static/img/products/catalog/accessories/acc-0228.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '404b9a3d-9dcb-513b-8ba0-b1edf5267523',
    'ACC-0229',
    'Passport Holder',
    'Passport Holder from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    230.24,
    'USD',
    '/static/img/products/catalog/accessories/acc-0229.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd5d5604c-db43-562a-b4d5-f2f7a276dd3b',
    'ACC-0230',
    'Keychain',
    'Keychain from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    233.49,
    'USD',
    '/static/img/products/catalog/accessories/acc-0230.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '5e312146-ecdb-53c8-917c-d485e6d94270',
    'ACC-0231',
    'Card Holder',
    'Card Holder from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    236.74,
    'USD',
    '/static/img/products/catalog/accessories/acc-0231.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f984f477-5c8b-579c-97dc-d6e6bfb105b0',
    'ACC-0232',
    'Umbrella',
    'Umbrella from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    239.99,
    'USD',
    '/static/img/products/catalog/accessories/acc-0232.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '2c133f80-5ae9-5c78-b86a-6f68e514279e',
    'ACC-0233',
    'Travel Pillow',
    'Travel Pillow from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    243.24,
    'USD',
    '/static/img/products/catalog/accessories/acc-0233.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '87c39077-0af5-58b7-b672-42fb0a90787b',
    'ACC-0234',
    'Luggage Tag',
    'Luggage Tag from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    246.49,
    'USD',
    '/static/img/products/catalog/accessories/acc-0234.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '80dd3d80-5f1a-5573-9744-8c4169c088bb',
    'ACC-0235',
    'Tote Bag',
    'Tote Bag from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    249.74,
    'USD',
    '/static/img/products/catalog/accessories/acc-0235.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '6c77a0db-db8d-5e16-a460-1d7357a3c33e',
    'ACC-0236',
    'Bracelet',
    'Bracelet from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    252.99,
    'USD',
    '/static/img/products/catalog/accessories/acc-0236.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'e58f3fe5-45fb-5f08-aeb1-59d08cbd6d87',
    'ACC-0237',
    'Pendant Necklace',
    'Pendant Necklace from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    256.24,
    'USD',
    '/static/img/products/catalog/accessories/acc-0237.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '3438f98a-0f42-5c3f-9d4c-c1507b162834',
    'ACC-0238',
    'Stud Earrings',
    'Stud Earrings from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    259.49,
    'USD',
    '/static/img/products/catalog/accessories/acc-0238.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'f0108a3d-f91d-576a-ac83-2e4983d00031',
    'ACC-0239',
    'Hair Band Set',
    'Hair Band Set from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    262.74,
    'USD',
    '/static/img/products/catalog/accessories/acc-0239.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    'd3437fb4-35d2-5448-8804-acac93da3f3c',
    'ACC-0240',
    'Phone Case',
    'Phone Case from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    5.99,
    'USD',
    '/static/img/products/catalog/accessories/acc-0240.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
),
(
    '926967f9-64ce-5b30-a0b5-7e8012d61ae6',
    'ACC-0241',
    'Shoe Care Kit',
    'Shoe Care Kit from our accessories collection, selected for everyday use, reliable quality, and modern design.',
    'accessories',
    9.24,
    'USD',
    '/static/img/products/catalog/accessories/acc-0241.svg',
    'ACTIVE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
)
ON CONFLICT (sku) DO NOTHING;
